### ISSUE TITLE
No JSON could be decoded

### ISSUE THREAD

**Issue by gurisko** [ebrian/instamanage#4]
It seems that Instagram changed their endpoint. `followers` ([link](https://github.com/ebrian/instamanage/blob/777260b6b58b23b32e7697a938d080545883cef1/instamanage.py#L134)) gets 404 back.

console output:
```
attempting login...
logged in successfully
building follower list...
Traceback (most recent call last):
  File "instamanage.py", line 419, in <module>
    menu()
  File "instamanage.py", line 94, in menu
    start_sync()
  File "instamanage.py", line 135, in start_sync
    data = json.loads(followers.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
logging out...
```

**Comment by realtux** [comment]
Well that's lame :/

**Comment by tducasse** [comment]
> Well that's lame :/

Exactly what I was thinking haha

I think they changed their endpoint, I read about them deprecating their _/query_ route...

The graphql api seems available at _/graphql/query_ now.

**Comment by elfey** [comment]
If anyone finds the fix to this, let me know. I'm working on figuring it out right now as well.

**Comment by realtux** [comment]
yes, it looks like they are using `/graphql/query`. rather than a custom string as a post var, they are doing everything as querystring params. the response looks similar. this probably isn't that hard to fix.

**Comment by elfey** [comment]
@ebrian I've got the URL's and basic stuff figured out, but now I'm trying to narrow it down to get the specific query. Right now just doing the plain URL without a GraphQL query being posted gets me the `followed_by` information only. How did you find out the GraphQL query being sent?

It seems like each query has a different `query_id`.

**Comment by gurisko** [comment]
Is anyone looking into this?

**Comment by danperrout** [comment]
Same issue here...

**Comment by katepratik** [comment]
@ebrian So have you fixed it yet?

**Comment by realtux** [comment]
@katepratik No. This project is no longer maintained. I personally don't have any free time to get this fixed. You are welcome, of course, to fork the repo and make the fix. I'm sure it wouldn't take longer than an hour or two.
